name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install software-properties-common -y
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update -y
        sudo apt-get install -y gcc-13 valgrind

    - name: Set up gcc-13
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 90

    - name: Check versions
      run: |
        gcc --version
        make --version

    - name: make build
      run: make build

    - name: make test
      run: make test

    # - name: make memcheck
    #   run: make memcheck


